pub const INITIAL_CONTROLLER_EPOCH: u128 = 0;
pub const INITIAL_CONTROLLER_EPOCH_ZK_VERSION: i32 = 0;

pub const EVENT_CONTROLLER_CHANGE: u32 = 0;
pub const EVENT_RE_ELECT: u32 = 1;
pub const EVENT_BROKER_CHANGE: u32 = 2;
pub const EVENT_BROKER_MODIFICATION: u32 = 3;
pub const EVENT_TOPIC_CHANGE: u32 = 4;
pub const EVENT_STARTUP: u32 = 5;
pub const EVENT_REPLICA_LEADER_ELECTION: u32 = 6;
pub const EVENT_CONTROLLER_SHUTDOWN: u32 = 7;
pub const EVENT_LEADER_AND_ISR_RESPONSE_RECEIVED: u32 = 8;
pub const EVENT_UPDATE_METADATA_RESPONSE_RECEIVED: u32 = 9;
pub const EVENT_REGISTER_BROKER_AND_REELECT: u32 = 10;
pub const EVENT_ISR_CHANGE_NOTIFICATION: u32 = 11;
