pub const INITIAL_CONTROLLER_EPOCH: u128 = 0;
pub const INITIAL_CONTROLLER_EPOCH_ZK_VERSION: i32 = 0;

pub const EVENT_CONTROLLER_CHANGE: u32 = 0;
pub const EVENT_RE_ELECT: u32 = 1;
pub const EVENT_BROKER_CHANGE: u32 = 2;
pub const EVENT_BROKER_MODIFICATION: u32 = 3;
pub const EVENT_TOPIC_CHNAGE: u32 = 4;
pub const EVENT_STARTUP: u32 = 5;